apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: demo
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/agus-3rd-yoga/argocd-demo.git

