apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-web
  name: apache-web
  namespace: demo
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  #- nodePort: 31797
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-web
  sessionAffinity: None
  #type: NodePort
status:
  loadBalancer: {}
